### PR TITLE
Do nothing when a number out of range is entered in password page

### PR DESCRIPTION
**Pull request by enokawa**
Hi, thank you for your great service!

An error occurred when entering a value that is not allowed in password page.
And now that I have fixed that problem, please review.

Below is a video for reference.

https://user-images.githubusercontent.com/4405012/233688103-c607bbab-b73b-46f2-9043-e20603f3dea2.mov

### CODE REVIEW

**Comment by y13i** [comment]
@enokawa Cool! Thanks for pointing out this.

But this change makes it almost impossible to directly input a new length value by keyboard (except `8` or `9`).

So the below should be a bit better. What do you think?

```ts
                  onChange={(event) => {
                    const newLength = parseInt(event.target.value, 10);
                    setLength(newLength);

                    if (newLength >= minLength && newLength <= maxLength) {
                      setPasswordsDebounced({
                        type: passwordType,
                        length: newLength,
                      });
                    }
                  }}
```

**Comment by enokawa** [comment]
@y13i Thanks!
It looks better than my code!

I'll fix it later.

**Comment by enokawa** [comment]
@y13i I modified the code you provided, but I got an error.

error

Continue debugging.

**Comment by y13i** [comment]
That error looks to be due to a lack of `NaN` check. So the following would be good.

```ts
                  onChange={(event) => {
                    const newLength = parseInt(event.target.value, 10);

                    if (
                      isNaN(newLength) ||
                      newLength < minLength ||
                      newLength > maxLength
                    ) {
                      return;
                    }

                    setLength(newLength);
                    setPasswordsDebounced({
                      type: passwordType,
                      length: newLength,
                    });
                  }}
```

Also, I thought `setLength(newLength)` without max/min check was OK but now I think your idea should be better. Plus, I was mistaken that `minLength` was `8` (actually it's `4`) in my last comment.

Once you add `NaN` check I'll merge it ✌️ Thanks!

**Comment by enokawa** [comment]
@y13i Thanks! I Added `NaN` check.

**Pull request merged**
